export const products = [
    {
        id: 1,
        title: "HoogTech Mern Stack Project",
        img: "https://i.ibb.co/Fs4DmfW/hoogtech.png",
        img1: "https://i.ibb.co/CmxzNGN/hoogtech-2.png",
        img2: "https://i.ibb.co/6wv4mxW/hoogtech-3.png",
        ft1: "CRUD Compatible Website (Users can Create, Remove, Update, Delete)",
        ft2: "Custom User Dashboard when logs in",
        ft3: "Fully Dynamic Website and JWT Token Implemented for Secured API",
        ft4: "Backend and Database Integrated Website",
        ft5: "100% Secured Firebase Authentication",
        link: "https://hoogtech-58f30.web.app",
        gitClient: "https://github.com/Safin-Ahmed/hoogtech-client",
        gitServer: "https://github.com/Safin-Ahmed/hoogtech-server"
    },
    {
        id: 2,
        title: "Voyage Tourism Mern Stack Project",
        img: "https://i.ibb.co/bdrrZGZ/voyage.png",
        img1: "https://i.ibb.co/vYLh1Jv/voyage-2.png",
        img2: "https://i.ibb.co/6szkKVv/voyage-3.png",
        ft1: "CRUD Compatible Website (Users can Create, Remove, Update, Delete)",
        ft2: "Custom User Dashboard when logs in",
        ft3: "Fully Dynamic Website and JWT Token Implemented for Secured API",
        ft4: "Backend and Database Integrated Website",
        ft5: "100% Secured Firebase Authentication",
        link: "https://tourism-website-39175.web.app/ ",
        gitClient: "https://github.com/Safin-Ahmed/voyage-client",
        gitServer: "https://github.com/Safin-Ahmed/voyage-server"
    },
    {
        id: 3,
        title: "VetCare React Project",
        img: "https://i.ibb.co/jrt5y6m/vetcare.png",
        img1: "https://i.ibb.co/GsQvNfD/vetcare-3.png",
        img2: "https://i.ibb.co/DtjbGP4/vetcare-4.png",
        ft1: "React Single Page Application",
        ft2: "Firebase Authentication with Google Auth Provider",
        ft3: "Secured Google Authentication Config with Environment Variable",
        ft4: "Private Route Protected Website",
        ft5: "Fully Dynamic Website",
        link: "https://healthcare-website-9bd6f.web.app/",
        gitLink: "https://github.com/Safin-Ahmed/vetcare-react",
    },
    {
        id: 4,
        title: "DevCode Educational React Project",
        img: "https://i.ibb.co/HtL5446/devcode.png",
        img1: "https://i.ibb.co/XDvqJsD/devocde-2.png",
        img2: "https://i.ibb.co/kQqTKLH/devcode-3.png",
        ft1: "CRUD Compatible Website (Users can Create, Remove, Update, Delete)",
        ft2: "Custom User Dashboard when logs in",
        ft3: "Fully Dynamic Website and JWT Token Implemented for Secured API",
        ft4: "Backend and Database Integrated Website",
        ft5: "100% Secured Firebase Authentication",
        link: "https://safin-devcode.netlify.app/",
        gitLink: "https://github.com/Safin-Ahmed/devcode-react"
    },
    {
        id: 5,
        title: "Shopify Academy Store",
        img: "https://i.ibb.co/zVv8GfT/the-academy.png",
        img1: "https://i.ibb.co/mGXgx9c/academy-2.png",
        img2: "https://i.ibb.co/JyRX1Yb/academy-3.png",
        ft1: "CRUD Compatible Website (Users can Create, Remove, Update, Delete)",
        ft2: "Custom User Dashboard when logs in",
        ft3: "Fully Dynamic Website and JWT Token Implemented for Secured API",
        ft4: "Backend and Database Integrated Website",
        ft5: "100% Secured Firebase Authentication",
        link: "https://kursagenten2022.myshopify.com/pages/safin",
    },
    {
        id: 6,
        title: "Shopify E-commerce Store",
        img: "https://i.ibb.co/swzgstf/abby.png",
        img1: "https://i.ibb.co/NyqJ38s/abby-2.png",
        img2: "https://i.ibb.co/CMb1ZHq/abby3.png",
        ft1: "CRUD Compatible Website (Users can Create, Remove, Update, Delete)",
        ft2: "Custom User Dashboard when logs in",
        ft3: "Fully Dynamic Website and JWT Token Implemented for Secured API",
        ft4: "Backend and Database Integrated Website",
        ft5: "100% Secured Firebase Authentication",
        link: "https://abbylabel.myshopify.com/",
    },
];